### ISSUE TITLE
"Always open in MacDown" doesn't work from Finder.

### ISSUE THREAD

**Issue by marcelvoss** [MacDownApp/macdown#175]

**Comment by andreas-manusm** [comment]
@uranusjr many thanks for the great work! @aaronraimist as well for pointing to the right place, it is  really annoying waiting vor xcode for fast typing...

**Comment by commadelimited** [comment]
I'm having this same issue in MacDown 0.6.4. Right clicking and selecting "Always Open With..." will open the select .md file in MacDown, but it doesn't remember the selection.

FWIW @aaronraimist, that IS how OS X is supposed to work. Selecting "Always Open With..." is a system level change and should result in a file always being opened with MacDown. It worked that way with Mou, and it works that way with other file types. Your suggestion _does_ work, but the result should be the same as if you took the right click approach.

**Comment by franklinyu** [comment]
@commadelimited I don't think so. According to my experiments, the right click approach does *not* change how Finder opens *all* `*.md` files, but it changes how Finder opens *that* `foo.md` file (I verified that with Sublime Text). Therefore, if you need to change the file type association, I believe you have to follow @aaronraimist.

**Comment by ik666** [comment]
Actully, the "change all" button makes only sense, if @commadelimited assumption is correct and I believe it is.
Also see [this discussion](https://discussions.apple.com/thread/6742323?start=0&tstart=0).
MacDown is therefore almost unusable ... to bad.

**Comment by niklasberglund** [comment]
Haven't looked into it but got a feeling this might be related to UTI. MacDown currently accepts _net.daringfireball.markdown_, _public.text_, _public.data_. I think .mmd files uses another UTI?

**Comment by uranusjr** [comment]
Wait, what is an `.mmd` file anyway? In any case, if it is a text-based format, it *should* conform to `public.text` (or at the very least `public.data`, which denotes a byte stream), and therefore able to be opened by MacDown. The file creator should fix its extension registration if it doesn’t. MacDown can’t help it. (Well, technically we can by accepting whatever UTI it declares itself as, but that’s not how this identifier system works.)

**Comment by niklasberglund** [comment]
According to the edit of this post from daringfireball.net `public.plain-text` is a better choice than `public.text` https://daringfireball.net/linked/2011/08/05/markdown-uti

**Comment by ik666** [comment]
I got it working. Running your command `mdls -name kMDItemContentType readme.md` gave me
`kMDItemContentType = "net.daringfireball.markdown"`. After applying "always open with ..." on one `readme.md` file, all files of type `*.md` are now being opened by MacDown. Maybe I had an issue with file permissions ...

**Comment by franklinyu** [comment]
Sorry guys, but I still don't get it. What's the issue with current behavior of MacDown? I fail to see any.

**Comment by niklasberglund** [comment]
@franklinyu haha agreed. I think UTI might be related to the problem @jgclark is having, but there shouldn't be any other issue here.

> Selecting "Always open in ..." for a file works, but then double-clicking that file later opens it in my default editor. Double-clicking on a file with the same extension (.mmd in this case) also opens it in my default editor.

**Comment by franklinyu** [comment]
@niklasberglund So maybe I can close this issue? (And keep comment open, of course.)

**Comment by ik666** [comment]
In my optionon yes: @aaronraimist solution works.

**Comment by niklasberglund** [comment]
@franklinyu I think so. Created a small PR for the UTI change. It's just a tiny improvement which shouldn't make much of a difference.
